Nested try-catch block :-
========================

 public class test 
 {
   public static void main (String []args)
   {
     int a = 10 ;
     int b = 0 ;
     int c ;
     try //1
       {
         try//2
            {
              try//3
                {
                 
                 int []arr = {1,2,3,4};
                 System.out.println(arr[10]);
                }
                 catch(ArithmeticException e)
                {
                  System.out.println(e);
                  System.out.println("Try 3");
                }
            }
              catch(ArithmeticException e)
                {
                  System.out.println(e);
                  System.out.println("Try 2");
                }  
     
            }
               catch(ArrayIndexOutOfBoundsException e)
                {
                  System.out.println(e);
                  System.out.println("Try 1");
                }
                catch (Exception e) {  
                System.out.print(e);  
                
        }  
   }
 }